"""בדיקות בניית INI, חילוץ מטא-דאטה מ-G-code וחישוב עלות."""
from pathlib import Path

import pytest

from app.pipeline.stages.slicing import PRESETS, build_ini, compute_cost, parse_gcode_metadata


@pytest.fixture
def base_ini(tmp_path: Path) -> Path:
    p = tmp_path / "base.ini"
    p.write_text(
        "bed_shape = 0x0,250x0,250x210,0x210\n"
        "nozzle_diameter = 0.4\n"
        "max_print_height = 220\n"
        "gcode_flavor = marlin2\n",
        encoding="utf-8",
    )
    return p


def _to_dict(ini_text: str) -> dict:
    out = {}
    for line in ini_text.splitlines():
        if "=" in line:
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def test_build_ini_merges_preset_and_material(base_ini):
    cfg = _to_dict(build_ini(base_ini, "quality", "PETG", None))
    assert cfg["layer_height"] == "0.12"
    assert cfg["temperature"] == "240"
    assert cfg["bed_temperature"] == "85"
    assert cfg["bed_shape"].startswith("0x0")


def test_build_ini_advanced_overrides(base_ini):
    adv = {"layer_height": 0.15, "infill_pct": 42, "supports": "tree",
           "brim": True, "nozzle_temp": 218}
    cfg = _to_dict(build_ini(base_ini, "standard", "PLA", adv))
    assert cfg["layer_height"] == "0.15"
    assert cfg["fill_density"] == "42%"
    assert cfg["support_material_style"] == "organic"
    assert cfg["brim_width"] == "5"
    assert cfg["temperature"] == "218"


def test_parse_gcode_metadata(tmp_path):
    g = tmp_path / "t.gcode"
    g.write_text(
        "; generated by PrusaSlicer\n"
        "G1 X10 Y20 Z0.2 E1 F1200\n"
        ";LAYER_CHANGE\n"
        "G1 X100.5 Y150 E2\n"
        ";LAYER_CHANGE\n"
        "G1 X50 Y50 Z10.4 E3\n"
        "; filament used [mm] = 1234.5\n"
        "; filament used [g] = 3.7\n"
        "; estimated printing time (normal mode) = 1h 32m 10s\n",
        encoding="utf-8",
    )
    meta = parse_gcode_metadata(g)
    assert meta["time_s"] == 3600 + 32 * 60 + 10
    assert meta["filament_mm"] == 1234.5
    assert meta["filament_g"] == 3.7
    assert meta["layers"] == 2
    assert meta["x_range"] == [10.0, 100.5]
    assert meta["z_max"] == 10.4


def test_compute_cost_positive():
    cost = compute_cost({"filament_g": 100, "time_s": 7200})
    assert cost["filament_ils"] > 0
    assert cost["electricity_ils"] > 0
    assert cost["total_ils"] == round(cost["filament_ils"] + cost["electricity_ils"], 2)


def test_presets_ordering():
    assert PRESETS["draft"]["layer_height"] > PRESETS["standard"]["layer_height"] > PRESETS["quality"]["layer_height"]
