# --- Photo2Print generated base profile ---
filament_diameter = 1.75
skirts = 1
skirt_distance = 3
brim_width = 0
support_material = 1
support_material_auto = 1
support_material_threshold = 50
fill_pattern = grid
top_solid_layers = 4
bottom_solid_layers = 3
seam_position = nearest
avoid_crossing_perimeters = 1
travel_speed = 150
perimeter_speed = 45
infill_speed = 80
first_layer_speed = 20
retract_length = 0.8
retract_speed = 35
min_skirt_length = 4
bed_shape = 0x0,220x0,220x220,0x220
max_print_height = 250
nozzle_diameter = 0.4
gcode_flavor = marlin2
